### ISSUE TITLE
Numbers In the Sudoku Cells need to be centered both vertically and horizontally

### ISSUE THREAD

**Issue by v-gajjar** [v-gajjar/SudokuApp#14]
Currently the numbers are rendered at the top of the cell, and centred only vertically.

**Comment by DGrothe-PhD** [comment]
At least in the pictures in the readme it looks quite accurate.

**Comment by v-gajjar** [comment]
> At least in the pictures in the readme it looks quite accurate.

This is how it the implementation looks: 

![image](https://github.com/user-attachments/assets/e87783e1-42b6-45fb-b4b9-826e469b6aaa)

**Comment by v-gajjar** [comment]
Implemented a solution that uses Flex and is pushed to a branch named fix-cell-number-alignment. Commit id: e6d1a42

**Comment by v-gajjar** [comment]
How it looks with Flex: 

![image](https://github.com/user-attachments/assets/040f35ff-0b69-4a98-a87c-d0d9c1adc5bf)
