### ISSUE TITLE
The boolean logic for inverting fillMode and guessMode isn't working

### ISSUE THREAD

**Issue by v-gajjar** [v-gajjar/SudokuApp#23]
the following code in toggleBetweenFillAndGuessMode() function does not appear to be having any effect - the values are not inverted. 

`  guessMode === true ? false : true;
  fillMode === true ? false : true;`

**Comment by v-gajjar** [comment]
A simple solution that works is to use boolean negation logic:

`guessMode != guessMode;
fillMode != fillMode;`

changes pushed to fix_toggleBetweenFillAndGuessMode_logic branch

**Comment by JoleneKearse** [comment]
Closed with commit 0b2e56b
